#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  df
#  
#  Copyright 2023 Felipe Souza <lubuntu@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

def df():
    if os.name == "posix": 
        df_output = os.popen("df -h").read()
    elif os.name == "nt": 
        df_output = os.popen("wmic logicaldisk get deviceid,size,freespace").read()
    else:
        print("df: operatioonal system not supported")
        return

    lines = df_output.strip().split("\n")
    
    if os.name == "posix": 
        headers = lines[0].split()
        data = [line.split() for line in lines[1:]]
    elif os.name == "nt": 
        headers = ["DeviceID", "Size", "FreeSpace"]
        data = [line.split() for line in lines[1:] if line.strip() != ""]
    else:
        return
    
   
    print("\t".join(headers))
    
    for row in data:
        print("\t".join(row))

df()

