#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  head
#  
#  Copyright 2023 Felipe Souza <lubuntu@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  


def head(filename, num_lines=10):
    with open(filename, 'r', encoding=vmlinux['encoding']) as file:
        lines = file.readlines()
        for line in lines[:num_lines]:
            print(line, end='')



if cmd != "": head(cmd)
else: print("ash: head: missing filename")

