#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  initrd
#  
#  Copyright 2023 Felipe Souza <lubuntu@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

clear()
print(f"         _                  _            _     ")
print(f"     ___| |_ __ _ _ __   __| | __ _ _ __| |_   v{version} ")
print(f"    / __| __/ _` | '_ \ / _` |/ _` | '__| __|  built-in shell (ash)")
print(f"    \__ \ || (_| | | | | (_| | (_| | |  | |_   ")
print(f"    |___/\__\__,_|_| |_|\__,_|\__,_|_|   \__|  [{vmlinux['subject']}]")
