#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  uname
#  
#  Copyright 2023 Felipe Souza <lubuntu@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

if cmd != "":
    if "-a" in cmd:
        print(f"System: {platform.system()}")
        print(f"Node: {platform.node()}")
        print(f"Release: {platform.release()}")
        print(f"Version: {platform.version()}")
        print(f"Machine: {platform.machine()}")
        
    elif "-s" in cmd: print(platform.system())
    elif "-n" in cmd: print(platform.node())
    elif "-r" in cmd: print(platform.release())
    elif "-v" in cmd: print(platform.version())
    elif "-m" in cmd: print(platform.machine())

    else: print(system, release)
        
else: print(system, release)
