#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  wget
#  
#  Copyright 2023 Felipe Souza <fetuber4095@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#   


try: url = cmd.split()[0]
except: url = input("url: ").strip()

if url != "":
	try: output_file = cmd.split()[1]
	except: output_file = input("filename: ").strip()
	
	if output_file != "": 
		if wget(url, output_file): print(f"{sh}: wget: donwloaded {output_file}")
		else: print(f"{sh}: wget: donwload failed [Errno 309]")
	else: print(f"{sh}: wget: invalid filename")
else: print(f"{sh}: wget: no url specified")
