#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  insiders
#  
#  Copyright 2023 Felipe Souza <lubuntu@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

class InsiderApplication:
	def __init__(self, token):
		with open(token, "r") as self.token:
			self.token = json.load(self.token)
		
		self.build = "08H1"
		
		clear()
		print(f"     _           _     _                ")
		print(f"    (_)_ __  ___(_) __| | ___ _ __ ___   Token '{self.token['token-name']}'")
		print(f"    | | '_ \/ __| |/ _` |/ _ \ '__/ __|  Build [{self.build}]")
		print(f"    | | | | \__ \ | (_| |  __/ |  \__ \ ")
		print(f"    |_|_| |_|___/_|\__,_|\___|_|  |___/ \n")
		print(f"Insider Package are comming. . .")
		
		
InsiderApplication(cmd)
	
