#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
#  test
#  
#  Copyright 2023 Felipe Souza <lubuntu@lubuntu>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

from etc.pyutils import *

input("ENTER for copy file 'vmlinux' to 'lts'"), cpfiles("vmlinux", "lts")
input("ENTER for rename 'lts' to 'test2'"), mvfiles("lts", "test2")
input("ENTER to list existent files on directory\n"), print(listdir("."))
input("ENTER to create the '/tmp' dir"), mkdir("tmp")
input("ENTER to remove '/tmp' dir"), rmdir("tmp")
input("ENTER to remove file 'test2'"), remove("test2")
input("ENTER to show 'vmlinux' file content"), print(openfile("vmlinux"))
